#!/bin/bash

function main ()
{
echo
echo
echo "reading in planet.osm"
echo
sudo su postgres sh -c "echo 'DROP DATABASE openstreetmap_tmp;' | psql"
sudo su postgres sh -c "createdb -E UTF8 -O openstreetmap openstreetmap_tmp"
sudo su postgres sh -c "psql -d openstreetmap_tmp < /usr/share/postgresql/8.4/contrib/btree_gist.sql"
rake db:migrate RAILS_ENV=tmp
bzcat tmp/planet-latest.osm.bz2 | osmosis --read-xml-0.6 file=. --write-apidb-0.6 populateCurrentTables=yes host="localhost" database="openstreetmap_tmp" user="openstreetmap" password="dfkiteam" validateSchemaVersion=no
}

main 2>&1 | tee -a log/reload-data.log
